<!DOCTYPE html>
<html lang='en'>
<head>

    <title>Project 1 - High/Low Guessing game</title>
    <meta charset='utf-8'>
    <link href=data:, rel=icon>     
    <link rel="stylesheet" href="style.css" />

</head>

<body>

<div class="container">
<img src="logo.png" alt="logo" /><br />


 <div id="str"> 
   <?php if (!isset($results)) {  ?>
Come on!!!<br />Guess a number that is an integer from 1 to 10;

<?php } else { if ($invalidGuess){ ?>
  Invalid entry!<br />Your guess must be an integer from 1 to 10
  <?php } elseif ($number==$guess){  ?>
    Hurray! You guessed it right. The number was
    <?php echo $number; } elseif (!$failGame and $number<$guess){ ?>
      Woahhh that's too high. Try again!. Your guess was:
    <?php echo $guess;} elseif (!$failGame and $number>$guess){  ?>
      Too low my friend. Guess again! Your guess was:
    <?php echo $guess;} elseif ($failGame){  ?>
      You lost! The correct answer was
    <?php echo $number;} ?>
  <?php  } ?>
</div> <br />

<form  action="process.php" method="post">

 <?php if (is_null($_SESSION['results'])) {   
  ?>
  <input type="text" name="guess" /><br /> 
<input type="submit" name="submit" value="GUESS"/><br />  
<?php  } elseif (isset($results)) {if (!$failGame and $number!==(int)$guess) { ?>
  <input type="text" name="guess" /><br /> 
<input type="submit" name="submit" value="GUESS"/><br />  
<?php  } else { ?>
<input type="submit" name="replay" value="Play again"/><br /> 
<?php  }} ?> <input type="hidden" name="counter" /> 

</form>


     <br />
   <div id="attempts">  
    You have <?php  isset($results) ? print $counter : print "4"; ?> attempts left at this game.
    </div>
 </div> 

 <h2>Mechanics</h2>
 <ul>
   <li>A random number is generated by server.</li>
 <li>User inputs the number and submits via the button.</li>
 <li>The guessed number is matched to the generated number.</li>
 <li>The user has 4 attempts to guess the right number.</li>
 <li>If the guess is wrong, the counter of attempts is decreased by one.</li>
 <li>If the user guesses the number wrong all 4 times, the game is lost and the user has the option to play again.</li>
<li>If successful, the user can play the game again and the counter of attempts is reset.</li></ul>
</br>
</br>







</body>
</html>