<!DOCTYPE html>
<html lang='en'>
<head>

    <title>Project 1 - High/Low Guessing game</title>
    <meta charset='utf-8'>
    <link href=data:, rel=icon>     
    <link rel="stylesheet" href="style.css" />

</head>

<body>

<div class="container">
<img src="logo.png" alt="logo" /><br />
<div id="str"><?php echo $str
 ?></div> <br />
 
   <div id="attempts">  <?php echo $attempts
 ?> </div>
 </div>

 <h2>Mechanics</h2>
 <ul>
   <li>A random number is generated by server.</li>
 <li>A user guess number is randomly generated by server.</li>
 <li>The user guessed number is matched to the random number on page refresh.</li>
 <li>There are 4 attempts to guess the right number.</li>
 <li>If the guess is wrong, the counter of attempts is decreased by one.</li>
 <li>If the guesses are wrong all 4 times, the game is lost and the user has the option to play again.</li>
<li>If successful, the game is refreshed and the counter of attempts is reset.</li></ul>
<li>For real world and more complicated version of this game with user input, check the link <a href="http://e2p1.kamalzadeh.me/">http://e2p1.kamalzadeh.me/</a></li></ul>
</br>
</br>

</body>
</html>